name: main workflow
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name:  build test
      - name: first build test
        run: |
          echo "time is $(date)"
          currentTimestamp=$(date +%Y-%m-%d-%H-%M-%S)
          touch "executed-${currentTimestamp}.txt"
  second-build:
    runs-on: self-hosted
    steps:
      - name:  second build test
        run: echo "time is $(date)"
        shell: bash
