name: main workflow
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name:  build test
      - name: step1
        run: echo "Integrating..."
      - name: step2
        run: echo "time is $(date)"
        shell: bash
  second-build:
    runs-on: self-hosted
    steps:
      - name:  second build test
        run: echo "time is $(date)"
        shell: bash
