name: CI - Integrate
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name:  build test
        run: echo "Integrating..."
        shell: bash
